// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbrvpckujpubdjoieuwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBicnZwY2t1anB1YmRqb2lldXd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NDEyNTYsImV4cCI6MjA1OTMxNzI1Nn0.ZcPpCfrLdNfgo4ymxAjv-_5OPQPGrzaVwx_ftd3ATU4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);